import Vue from 'vue'
import App from './App.vue'
import router from './router'
import store from './store'
import ViewUI from 'view-design'
import 'view-design/dist/styles/iview.css'
import ECharts from 'vue-echarts'
import { use } from 'echarts/core'
import {
  BarChart
} from 'echarts/charts'

use([
  BarChart
]);

import VueI18n from 'vue-i18n'

Vue.component('v-chart', ECharts)

Vue.use(ViewUI)
Vue.use(VueI18n)

const messages = {
  en: {
    message: {
      intro1: 'Planning realistic multistage implementation plans (i.e., roadmaps) from a management practice (BMP) scenario is essential to accomplish watershed management goals under practical conditions. Stepwise investment is one of the most common and comprehensive realistic conditions. However, current watershed planning systems still have not considered optimizing roadmaps overall under stepwise investment constraints. This study designed and developed a web-based watershed planning system to assist diverse stakeholders in iterative optimizing roadmaps, analyzing results, and reaching a consensus. The server side of the system integrated an optimization method of BMP implementation plans. The client side constructed a user-friendly interface and an iterative workflow for participatory analysis, including setting investment constraints and optimization parameters, visualizing and analyzing the spatiotemporal results from multiple perspectives, and finally reaching a consensus. The system was demonstrated in optimizing BMPs for soil erosion reduction in an agricultural watershed of southeastern China, to validate its iterative optimization process and the rationality and diversity of the optimized roadmaps.',
      intro2: 'This demo system is a participatory watershed planning system customized for the small watershed of Youwuzhen, Fujian, China. Aiming at the soil erosion governance objectives of the Youwuzhen watershed, the system can carry out watershed process simulation with data at 30m resolution. Starting from a selected BMP scenario, the system can optimize multistage implementation plans according to the stepwise investment constraints set by different stakeholders. This system can support stakeholders with different roles to participate in optimization and discussion and finally reach a consensus.',
      intro3: 'This study selected four representative BMPs that have been widely implemented in Youwuzhen watershed for soil and water conservation. Their brief descriptions are demonstrated in the figure below. The simulation period is from 2011 to 2017. The implementation period for the BMP scenario is from 2012 to 2016. The period of BMPs taking effect is from 2013 to 2017. The system optimizes the BMPs implementation plans within the five-year implementation period under the stepwise investment constraints set by stakeholders. The management goals are to maximize the soil erosion reduction rate and minimize the net present value of the net costs.', 
      introImg1:'../assets/img/customized/youwuzhen-bmps-en.jpg',
      intro4: '<h2>Test account</h2><p>Accounts with sample data for optimization results are shown in the table below. You can also register new accounts.</p>',
      intro5: '<h2>The iterative workflow</h2><p>1) view the historical optimization records of other stakeholders.</p><p>2) set the optimization name and notes.</p><p>3) set stepwise investment constraints.</p><p>4) set the parameters related to multi-objective optimization (optional) and submit the optimization task.</p><p>5) explore and analyze the optimization results and discuss or negotiate with other stakeholders if there are disagreements.</p><p>6) repeat steps 1 to 5 until a consensus is reached to determine the BMPs multistage implementation plan.</p>',
      intro6: '<h2>System Requirements</h2><p>Internet browsers (Chrome, Edge, Safari, and Firefox)</p>',
      title: 'Watershed planning system for optimizing multistage implementation plans under stepwise investment',
      logout: 'Logout',
      userLabel: 'Stakeholder',
      login: 'Login',
      loginError: 'Please login first.',
      register: 'Register',
      groupLabel: 'Group',
      roleLabel:'Role',
      nameLabel: 'Name',
      emailLabel: 'Email',
      passwordLabel: 'Password',
      loginSuccess: 'Login Successful!',
      registerSuccess: 'Register Successful!',
      exitSuccess: 'Exit successful!',
      runDemo: 'Run a demo',
      footer: 'Copyright © 2022. All rights reserved.',
      titleAnalyseResult: 'Exploratory analysis of optimization results',
      targetScenarioInfo:'Selected scenario information',
      targetScenarioStat: 'Selected scenario statistics',
      targetScenarioSpatial: 'Selected scenario spatial configuration',
      fj: 'CM',
      area: 'Area(km^2)',
      stlc: 'ABHMP',
      dxlgz: 'LQFI',
      jjlg:'EF',
      env: 'Environmetal',
      setNameAndNotes: 'Set optimization name and notes',
      optNotes:'Notes',
      plhdOptName: 'Customize a name for this optimization',
      plhdOptNotes: 'Enter some notes here',
      setStepwiseInvest: 'Set stepwise investment (unit: CNY 10,000)',
      tabMultistageInvestCap: 'Stepwise investment constraints',
      lblSetInvestCaps: 'Set annual investment constraints and the total investment cannot exceed ',
      budget: 'Currunt plan',
      remaining:'remain',
      overrun:'overrun',
      firstYear: 'First year',
      secondYear: 'Second year',
      thirdYear: 'Third year',
      fourthYear: 'Fourth year',
      fifthYear: 'Fifth year',
      bmpEnvMode: 'BMP environmental effectiveness mode',
      bmpVaryEffect: 'Time-varying effectiveness',
      bmpFixedEffect: 'Fixed effectiveness',
      optAlgorithmParameters: 'Optimization algorithm parameters',
      optObjectives: 'Optimization objectives',
      moAlgorithm: 'Multi-objective optimization algorithm',
      nsga:'NSGA-II',
      keyParameters: 'Key parameters',
      genNumbers: 'Generations',
      popSize: 'Population size',
      crossoverRate: 'Crossover rate',
      mutateRate: 'Mutate rate',
      selectRate: 'Select rate',
      reductionRate:'Reduction rate',
      reductionRateAxisLabel:'Soil erosion reduction rate (%)',
      accumReductionRate:'Accumulated reduction rate',
      accumReductionRateAxisLabelBreak:'Accumulated reduction\nrates (%)',
      maxReductionRate: 'Maximum soil erosion reduction rate',
      minNPV: 'Minimum net present value',
      npvBreak:'Net present value\n(unit: CNY 10,000)',
      yearAxisLabel:'Year',
      submitOpt: 'Submit optimization task',
      submitOptOnline:'Online optimization',
      optOnlineTip:'When the evolutionary generation is 2 and the population size is 4, the system can use coarse-resolution data (30m) for optimization on a single server. This process generally takes a few minutes. The results are only suitable for visualization and not for comparative analysis.',
      submitOptOffline:'Offline optimization',
      optOfflineTip:'The system will notify the administrator to submit optimization tasks on local HPC clusters using fine-resolution data (10m). This process generally takes several hours to several days, depending on the parameters. The results can be used for visualization and comparative analysis.',
      investExceed:'Total investment exceeds the limit! Please check the settings.',
      parametersCannotOptOnline:'This set of parameters does not support online optimization.',
      register: 'Register',
      optName: 'Optimization name',
      investType: 'Stepwise investment type',
      stepInvestLimits: 'Stepwise investment constraints (unit: CNY 10,000)',
      objective1: 'Objective 1',
      objective2: 'Objective 2',
      optRecords: 'Optimization records',
      compareRecords:'Compare',
      visualizeRecords:'Visualize',
      paretoFronts: 'Pareto fronts',
      showInvestIncome:'Show net cost',
      showInvest:'Show cost only',
      selectedRoadmapSpatial:'Spatial configuration of the selected roadmap',
      selectedRoadmapConstructionArea:'Construction area per year',
      selectedRoadmapEcoPerYear:'Economic summary per year',
      selectedRoadmapEcoPerYearBMP:'Economic summary per year and BMP',
      selectedRoadmapStepwise:'Roadmap stepwise effectiveness',
      saveCompareData:'Save',
      saveCompareDataSuccess:'Save candidates successfully!',
      saveCompareDataFail:'Save candidates failed!',
      selectRoadmaps:'Please select roadmaps to delete!',
      reachConsensus:'Consensus',
      deleteRoadmap:'Delete',
      altRoadmaps: 'Candidate roadmaps',
      initial: 'Initial',
      maintain: 'Maintain',
      benefit: 'Benefits',
      summary: 'Summary',
      viewOptResults: 'View optimization results',
      startOptimizationOnline:'Start Online Optimization!',
      submitOptSuccessOnline:'Online optimization finished! Please go to the optimization results page.',
      submitOptSuccessOffline:'Submit successfully! Offline optimization usually takes a long time, and we will notify you by email when complete.',
      submitOptFailed:'Submit failed! Please check the parameters.',
      optNameExists:'Optimization name already exists!',
      noOptHistory: 'No optimization record yet! If you have submitted, please wait patiently for the email notification.',
      discountRate: 'Discount rate (%)',
      roadmapNumInfo:'Only one roadmap can be chosen as consensus!',
      hasReachedConsensus:'Consensus has been reached!',
      roadmapAlreadyInList:'This roadmap has already in alternative list!',
      y1:'First year',
      y2: 'Second year',
      y3: 'Third year',
      y4: 'Fourth year',
      y5: 'Fifth year',
      selectCompareRecords:'Please select records to compare!',
      npv: 'Net present value (unit: CNY 10,000)',
      investAndBenefit:'Investments and benefits (unit: CNY 10,000)',
      viewAlternatives:'View candidates',
      addAlternatives:'Add candidates',
      tableNotes:'* The unit of initial cost, maintain cost and benefits is CNY 10,000.',
      reset: 'Reset All',
      backToParamterSetting:'Back to parameter settings'
    },
  },
  cn: {
    message: {
      intro1: '为流域管理措施情景规划切实可行的分阶段实施方案是流域管理目标实际落地的重要一环。分阶段投资是最常见、最有综合影响的现实因素之一。但是目前的流域规划系统缺乏在分阶段投资约束下优化多阶段实施方案的能力。在方法研究的基础上，本研究设计并实现了一种支持多角色利益相关者参与优化、达成共识并得到可行路线图的基于网络的流域规划系统。该系统服务端集成了支持管理措施（BMP）实施次序优化的优化方法，客户端支持调整实施方案优化方法输入参数、多角度可视化实施方案优化结果以及构建多角色参与的迭代式工作流。通过例证研究验证了系统设计与实现在迭代优化过程中的有效性，优化所得方案的合理性与多样性。',
      intro2: '本演示系统是面向中国福建汀江游屋圳小流域定制的参与式流域规划系统。针对游屋圳小流域的水土资源管理目标，本系统可以在30m分辨率的数据下开展流域过程模拟。本系统从给定的BMP情景出发，根据不同利益相关者设定的分年度投资条件，优化出符合要求的多阶段实施次序方案。本系统支持不同角色的利益相关者参与优化和讨论，并最终达成共识。',
      intro3: '本演示系统采用了4种在当地成功实施过的管理措施，详细介绍如下图所示。流域模拟时间段为2011年-2017年，2012年-2016年为BMP布设期，2013年-2017年为BMP生效期。系统在利益相关者设定的分阶段投资约束条件下优化5年布设期内BMP的实施次序，管理目标为最大化土壤侵蚀的削减率和最小化成本的净现值。',
      introImg1:'./assets/img/customized/youwuzhen-bmps-cn.jpg',
      intro4: '<h2>测试账号</h2><p>带有优化结果示例数据的账号：<b>利益相关者组: www@sss.com 密码: 123456</b> </p><p>也可自行注册新账号。</p>',
      intro5: '<h2>迭代式工作流</h2><p>第一步，查看其他利益相关者的历史优化记录。</p><p>第二步，设置优化的名称以及备注。</p><p>第三步，设置分阶段投资约束。</p><p>第四步，设置多目标优化相关参数，并提交优化任务。</p><p>第五步，探索分析优化结果，如果与其他利益相关者意见不一致的话，需要讨论或谈判。</p><p>第六步，重复一至五，直至达成共识，确定BMP多阶段实施方案。</p>',
      intro6: '<h2>系统运行要求</h2><p>Internet 浏览器 (Chrome, Edge, Safari, 以及Firefox)</p>',
      title: 'BMP情景实施次序优化原型系统',
      logout: '退出',
      userLabel: '利益相关者',
      login: '登录',
      loginError: '请先登录！',
      register: '注册',
      groupLabel: '利益相关者组',
      roleLabel:'角色',
      nameLabel: '用户名',
      emailLabel: '邮箱',
      passwordLabel: '密码',
      loginSuccess: '登录成功!',
      registerSuccess: '注册成功!',
      exitSuccess: '退出成功!',
      runDemo: '运行示例',
      footer: 'Copyright © 2022. All rights reserved.',
      titleAnalyseResult: '情景实施次序优化结果',
      targetScenarioInfo:'选定情景详情',
      targetScenarioStat: '选定情景统计信息',
      targetScenarioSpatial: '选定情景空间配置',
      fj: '封禁',
      area: '面积(km^2)',
      stlc: '生态林草',
      dxlgz:'低效林改造',
      jjlg: '经济林果',
      env: '环境效益',
      money: '经济净投入',
      t1: '请设置优化名称',
      setNameAndNotes: '设置优化基本信息',
      optNotes:'备注',
      tabMultistageInvestCap: '分阶段投资上限',
      lblSetInvestCaps: '设置每年投资上限并且总投资额不能超过 ',
      budget: '预算',
      remaining:'剩余',
      overrun:'超支',
      firstYear: '第一年',
      secondYear: '第二年',
      thirdYear: '第三年',
      fourthYear: '第四年',
      fifthYear: '第五年',
      bmpEnvMode: 'BMP效益变化模式',
      bmpVaryEffect: '变化效益',
      bmpFixedEffect: '固定效益',
      optAlgorithmParameters: '优化算法参数设置',
      optObjectives: '优化目标',
      moAlgorithm: '多目标优化算法',
      nsga:'NSGA-II',
      keyParameters: '关键参数',
      genNumbers: '进化代数',
      popSize: '种群规模',
      crossoverRate: '交叉率',
      mutateRate: '变异率',
      selectRate: '选择率',
      reductionRate:'侵蚀削减率',
      reductionRateAxisLabel:'土壤侵蚀削减率 (%)',
      accumReductionRate:'累计削减率',
      accumReductionRateAxisLabelBreak:'侵蚀削减率\n(%)',
      maxReductionRate: '土壤侵蚀削减率最大',
      minNPV: '净成本折现值最小',
      npvBreak:'净现值\n(万元)',
      yearAxisLabel:'年份',
      submitOpt: '开始实施次序优化',
      submitOptOnline:'在线优化',
      optOnlineTip:'当进化代数为2、种群规模为4时，系统可使用粗分辨率的数据(30m)在单台服务器上进行优化。优化过程一般耗时几分钟。优化结果仅适合可视化，不适合用于对比分析。',
      submitOptOffline:'离线优化',
      optOfflineTip:'系统将会通知管理员使用细分辨率数据(10m)在小型高性能计算集群上进行优化。优化过程一般耗时几小时到几天不等，取决于设定的参数。结果可用于可视化与对比分析。',
      investExceed:'总投资超限额！请检查设置。',
      parametersCannotOptOnline:'这组参数不支持在线优化.',
      register: '注册',
      optName: '优化名称',
      investType: '分阶段投资类型',
      stepInvestLimits: '分阶段投资金额（万元/年)',
      objective1: '目标1',
      objective2: '目标2',
      optRecords: '优化历史记录',
      compareRecords:'对比所选记录',
      visualizeRecords:'可视化所选记录',
      paretoFronts: '帕累托前沿对比',
      showInvestIncome:'关注投资和收入',
      showInvest:'只关注投资',
      selectedRoadmapSpatial:'选定路线图的空间配置',
      selectedRoadmapConstructionArea:'选定路线图的施工面积',
      selectedRoadmapEcoPerYear:'每年经济概况',
      selectedRoadmapEcoPerYearBMP:'每年每种BMP的经济情况',
      selectedRoadmapStepwise:'选定路线图的分阶段效益',
      saveCompareData:'保存',
      saveCompareDataSuccess:'保存成功！',
      saveCompareDataFail:'保存失败！',
      selectRoadmaps:'请选择要删除的路线图!',
      reachConsensus:'达成共识',
      deleteRoadmap:'删除',
      altRoadmaps: '候选路线图对比分析',
      initial: '初建费用',
      maintain: '运行费用',
      benefit: '收入',
      summary: '总计',
      viewOptResults: '查看优化结果',
      startOptimizationOnline:'开始在线优化！',
      submitOptSuccessOnline:'优化完成！请前往优化结果页面查看。',
      submitOptSuccessOffline:'提交成功！离线优化需要较长时间耗时，请等待邮件通知。',
      submitOptFailed:'提交失败!请检查参数',
      optNameExists:'优化名称已存在！',
      noOptHistory: '您还没有优化记录，如果已提交，请耐心等待邮件通知',
      discountRate: '折扣率%',
      plhdOptName: '请输入本次优化名称',
      plhdOptNotes: '可以写一些备注',
      setStepwiseInvest: '分阶段投资设置(万元)',
      roadmapNumInfo:'只能选择一个路线图作为共识!',
      hasReachedConsensus:'已达成共识!',
      roadmapAlreadyInList:'该路线图已在候选列表中!',     
      y1:'第1年',
      y2: '第2年',
      y3: '第3年',
      y4: '第4年',
      y5: '第5年',
      selectCompareRecords:'请选择要对比的历史记录!',
      npv: '净现值 (单位: 万元)',
      investAndBenefit:'投资与收入(万元)',
      viewAlternatives:'查看候选',
      addAlternatives:'添加候选',
      tableNotes:'*表格中初建费用、维护费用和收入的单位是万元。',
      reset: '重置所有参数',
      backToParamterSetting:'返回参数设置'
    }
  }
}

const i18n = new VueI18n({
  locale: 'en',
  // locale: 'cn',
  messages
})


Vue.config.productionTip = false

new Vue({
  router,
  store,
  render: h => h(App),
  i18n
}).$mount('#app')
